version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "pruebaTecnica123"
      ACCEPT_EULA: "Y"
    volumes:
      - db-data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - chn-network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - chn-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - chn-network

networks:
  chn-network:
    driver: bridge

volumes:
  db-data:
